os:
  - linux

language: c
sudo: true

git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

compiler:
  - gcc

## ----------------------------------------------------------------------
## Perform build:
## ----------------------------------------------------------------------

script:

  - ./configure
  - make
  - make check


## ----------------------------------------------------------------------
## Notification
## ----------------------------------------------------------------------
notifications:
  email:
    recipients:
      - jiayu2@asu.edu
    on_success: always
    on_failure: always
