#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/gsin
#
# IDENTIFICATION
#    src/backend/access/gsin/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/hippo
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hippo_utils.o hippo.o bitmap.o ewah_bitmap.o ewah_rlw.o ewah_io.o

include $(top_srcdir)/src/backend/common.mk
